# Basic dependabot.yml file that checks Gradle dependencies in the project
version: 2

updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "monthly"