inherit_gem:
    rubocop-shopify: rubocop.yml

Naming/AccessorMethodName:
  Enabled: false

Naming/PredicateName:
  Enabled: false

# Single quotes being faster is hardly measurable and only affects parse time.
# Enforcing double quotes reduces the times where you need to change them
# when introducing an interpolation. Use single quotes only if their semantics
# are needed.
Style/StringLiterals:
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 140
  IgnoredPatterns: ['^\s*#']

Metrics/ParameterLists:
  Max: 10
  MaxOptionalParameters: 5