name: Validate PRs

on:
  pull_request:
    branches:
      - develop

jobs:
  cancel_previous:
    name: Cancel previous runs
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ github.token }}

  validate_pr:
    name: Validate PRs on commit upload
    runs-on: ubuntu-latest
    needs: cancel_previous

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3

      - name: Install fastlane-plugin-android_build_tools deploy key
        uses: shimataro/ssh-key-action@v2.3.1
        with:
          key: ${{ secrets.ANDROID_BUILD_TOOLS_DEPLOY_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Set-up and configure JDK 11
        uses: actions/setup-java@v3.4.1
        with:
          distribution: zulu
          java-version: 11
          cache: gradle

      - name: Set-up and configure Ruby
        uses: ruby/setup-ruby@v1.133.0
        with:
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Install keysafe deploy key
        uses: shimataro/ssh-key-action@v2.3.1
        with:
          key: ${{ secrets.KEYSAFE_DEPLOY_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          if_key_exists: replace

      - name: Validate PR
        env:
          KEYSAFE_REPO_URL: ${{ secrets.KEYSAFE_REPO_URL }}
          APP_KEYSAFE_NAME: ${{ secrets.APP_KEYSAFE_NAME }}
          APP_KEYSAFE_PASSWORD: ${{ secrets.APP_KEYSAFE_PASSWORD }}
        run: |
          bundle exec fastlane validate_pr app_keysafe_name:"$APP_KEYSAFE_NAME" app_keysafe_password:"$APP_KEYSAFE_PASSWORD" artifact_type:AAB
